### ISSUE TITLE
Camera angle problem

### ISSUE THREAD

**Issue by AbdulMuhaymin** [WampyCakes/manim-rubikscube#3]
Without changing any of the code, when we run the basic examples from the plugin documentation, it produces the output without any error. However, every time the cube is placed on the lower-left corner of the screen, and some parts of it are even not inside the screen. I tried to scale it and rotate it to get it in the center, but I failed. Also, when I start camera rotation around the cube, the axis of rotation doesn't go through the cube. It goes outside the cube. So instead of a smooth cube rotation, I am getting a Rubik's cube following a circular horizontal loop.

**Comment by WampyCakes** [comment]
I'm going to assume you're on manim community v0.9.0. Try v0.8.0 and see if the issue persists. Something was messed up in a recent version of manimce (I think due to ManimCommunity/manim#1821). I'm thinking you're describing the problem found on the FlyingFrames documentation

Wrong
https://flyingframes.readthedocs.io/en/v0.9.0/ch1.html#Installing-Plugins

Correct
https://flyingframes.readthedocs.io/en/v0.8.0/ch1.html#Installing-Plugins

**Comment by AbdulMuhaymin** [comment]
Yes, that's exactly the problem. It is solved if I use manim ce v0.8.0. However, what should one do if one insists to use manim ce v0.9.0? I hope this fixes soon

**Comment by WampyCakes** [comment]
I am currently unsure, but as it is important, I will investigate it here sometime

**Comment by suhailsherif** [comment]
Why was this issue closed if it still persists?
In any case, this bug is very strange. Take the bug appearing in the flyingframes documentation. If you add a self.wait() after adding the cube, it seems to play fine. If you add the self.wait() and you skip the first animation, it's as if there was no wait command and everything works fine. I don't know how this could come about but I'm guessing it's a bug deep in manim's core.

**Comment by WampyCakes** [comment]
It shouldn't be closed, though this isn't an issue for manim-rubikscube so much as it is for Manim, AFAICT. Feel free to investigate the issue or file an issue on Manim's GitHub. I do not currently have time to investigate myself
